
server:
  port: 8503
spring:
  application:
    name: spring-cloud-user
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: provider-user   # 显示在consul 上面的 serviceId

