server:
  port: 8507
spring:
  application:
    name: spring-cloud-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: provider-order
#  为feign添加回退方法
feign:
  hystrix:
    enabled: true